project:
  type: website
  output-dir: docs 

website:
  title: "gabrielle smith"
  navbar:
    left:
      - href: index.qmd
        text: home
      - about.qmd
      - href: posts.qmd
        text: posts
      - href: workshops.qmd
        text: workshops
      - href: GS_CV.pdf
        text: cv
      - icon: github
        href: https://github.com/gabriellensmith

format:
  html:
    theme:
      - mystyles.scss
    mainfont: Alkalami
    toc: true

editor: visual

