name: Quarto Render to Docs

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "1.4.550"

      - name: Render Quarto Project
        run: quarto render
